FROM python:3.11-slim-bookworm
WORKDIR /app
COPY requirements.base.txt /app
RUN pip install --no-cache-dir -r requirements.base.txt
COPY . /app
EXPOSE 8000
ENV NAME "Fact-check API"
WORKDIR /app/src
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
