services:
  check:
    build:
      dockerfile: Dockerfile
    container_name: check
    env_file:
      - .env
    ports:
      - 8000:8000
    restart: always
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /data/volumes/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
  xinference:
    build:
      context: infra/xinference
      dockerfile: Dockerfile
    container_name: xinference
    ports:
      - 9997:9997
    volumes:
      - /data/volumes/xinference:/data
    environment:
      - XINFERENCE_HOME=/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
