name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push remote version
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.remote
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/check:remote

    - name: Build and Push local version
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.local
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/check:local


